# Generated by Django 3.2.5 on 2021-07-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='featured_listing',
            field=models.BooleanField(default=False),
        ),
    ]
