# Generated by Django 3.2.5 on 2021-07-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Client', 'Client')], default='Client', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='account_usage',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='https://i.pinimg.com/280x280_RS/c7/bc/9f/c7bc9fd3c036ae0572a0e9e597eaf37a.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
